[build]
  # This config assumes Netlify is building from the project ROOT
  command   = "npm run build"
  publish   = "frontend/dist"

# PROXY API REQUESTS TO RENDER
[[redirects]]
  from   = "/api/*"
  to     = "https://academic-policy.onrender.com/api/:splat"
  status = 200
  force  = true

# PROXY UPLOADS TO RENDER
[[redirects]]
  from   = "/uploads/*"
  to     = "https://academic-policy.onrender.com/uploads/:splat"
  status = 200
  force  = true

# React Router SPA redirect
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
